### ISSUE TITLE
Switch off Mailgun

### ISSUE THREAD

**Issue by arrdem** [TexasLAN/Omega#75] opened 2016-01-23 00:02 UTC
It's official. This is a priority. We need to be able to get emails both to members and to rushees without going back and forth over whether it went to spam or not.

**Comment by rob0rt** [comment] 2016-01-23 00:02
Sendgrid is a good alternative and doesn't suck

**Comment by spxrogers** [comment] 2016-01-23 00:05
fiiiiiiiinally. re: sendgrid, they have a free tier which is around 10k emails a month i believe.

**Comment by DrewRomanyk** [comment] 2016-01-23 07:36
We are using sendgrid, duplicate of this https://github.com/TexasLAN/Omega/issues/64

**Closed as completed by DrewRomanyk** 2016-01-23 07:36 UTC
Labels: enhancement
