### ISSUE TITLE
Finish password reset

### ISSUE THREAD

**Issue by rainiera** [TexasLAN/Omega#63] opened 2015-09-14 05:27 UTC
Build off of this: 595371e2d0365f

**Comment by coltwhaley** [comment] 2015-09-14 05:27
can you...like not?

**Comment by aaaanderson** [comment] 2015-09-14 05:28
same

**Comment by stevendiaz** [comment] 2015-09-14 05:30
:cool:

**Comment by rob0rt** [comment] 2015-09-15 16:08
Duplicate of #27

**Closed as completed** 2015-09-15 20:42 UTC
Labels: auth, API
